[package]
name = "aoc-2020"
version = "0.1.0"
edition = "2018"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.9.0"
rand = "0.7.3"
regex = "1.4.2"
lazy_static = "1.4.0"
